#define RAYGUI_IMPLEMENTATION

#include <raylib.h>
#include <raygui.h>
#include <string>
#include <vector>
#include "file/dir-file.h"
#include "file/mis-file/mis-file.h"
#include "file/wad-file.h"

std::vector<std::string> dirFilePaths = {
    "WARGAME.DIR"};

std::vector<std::string> wadFilePaths = {
    "DATOS/FONTS/COMAND2.WAD",
    "DATOS/FONTS/COMANDG.WAD",
    "DATOS/FONTS/COMANDO.WAD",
    "DATOS/FONTS/COMANDP.WAD",
    "DATOS/FONTS/SCORE.WAD",
    "DATOS/RECURSOS/BMPS/SPRITES/FASE0003.WAD",
    "DATOS/RECURSOS/BMPS/SPRITES/FASE0004.WAD",
    "DATOS/RECURSOS/BMPS/SPRITES/FASE0005.WAD",
    "DATOS/RECURSOS/BMPS/SPRITES/FASE0012.WAD",
    "DATOS/RECURSOS/BMPS/SYSTEM/CARAS/ARTIFIC.WAD",
    "DATOS/RECURSOS/BMPS/SYSTEM/CARAS/COMANDO.WAD",
    "DATOS/RECURSOS/BMPS/SYSTEM/CARAS/COMUN.WAD",
    "DATOS/RECURSOS/BMPS/SYSTEM/CARAS/CONDUC.WAD",
    "DATOS/RECURSOS/BMPS/SYSTEM/CARAS/ESPIA.WAD",
    "DATOS/RECURSOS/BMPS/SYSTEM/CARAS/FRANCOT.WAD",
    "DATOS/RECURSOS/BMPS/SYSTEM/CARAS/INGERIE.WAD",
    "DATOS/RECURSOS/BMPS/SYSTEM/CARAS/LANCHERO.WAD",
    "DATOS/RECURSOS/BMPS/SYSTEM/CARAS/PILOTO.WAD",
    "DATOS/RECURSOS/BMPS/SYSTEM/CARAS/PRESO.WAD",
    "DATOS/RECURSOS/BMPS/SYSTEM/GLOBAL/512X384.WAD",
    "DATOS/RECURSOS/BMPS/SYSTEM/GLOBAL/640X480.WAD",
    "DATOS/RECURSOS/BMPS/SYSTEM/GLOBAL/800X600.WAD",
    "DATOS/RECURSOS/BMPS/SYSTEM/GLOBAL/1024X768.WAD",
    "DATOS/RECURSOS/BMPS/SYSTEM/GLOBAL/1280X720.WAD",
    "DATOS/RECURSOS/BMPS/SYSTEM/GLOBAL/CURSORES.WAD",
    "DATOS/RECURSOS/BMPS/SYSTEM/GLOBAL/GLOBAL.WAD",
    "DATOS/RECURSOS/BMPS/SYSTEM/OPCIONES/ACTIVADO.WAD",
    "DATOS/RECURSOS/BMPS/SYSTEM/OPCIONES/ACTSENUE.WAD",
    "DATOS/RECURSOS/BMPS/SYSTEM/OPCIONES/ALICATE.WAD",
    "DATOS/RECURSOS/BMPS/SYSTEM/OPCIONES/ARPON.WAD",
    "DATOS/RECURSOS/BMPS/SYSTEM/OPCIONES/BALLESTA.WAD",
    "DATOS/RECURSOS/BMPS/SYSTEM/OPCIONES/BALSA.WAD",
    "DATOS/RECURSOS/BMPS/SYSTEM/OPCIONES/BOTIQUIN.WAD",
    "DATOS/RECURSOS/BMPS/SYSTEM/OPCIONES/CAMUFLAR.WAD",
    "DATOS/RECURSOS/BMPS/SYSTEM/OPCIONES/CARTUCH2.WAD",
    "DATOS/RECURSOS/BMPS/SYSTEM/OPCIONES/CARTUCHO.WAD",
    "DATOS/RECURSOS/BMPS/SYSTEM/OPCIONES/CEPO.WAD",
    "DATOS/RECURSOS/BMPS/SYSTEM/OPCIONES/CUCHILLO.WAD",
    "DATOS/RECURSOS/BMPS/SYSTEM/OPCIONES/FUSIL.WAD",
    "DATOS/RECURSOS/BMPS/SYSTEM/OPCIONES/GRANADA.WAD",
    "DATOS/RECURSOS/BMPS/SYSTEM/OPCIONES/INSIGNIA.WAD",
    "DATOS/RECURSOS/BMPS/SYSTEM/OPCIONES/JERIN.WAD",
    "DATOS/RECURSOS/BMPS/SYSTEM/OPCIONES/LANZALLA.WAD",
    "DATOS/RECURSOS/BMPS/SYSTEM/OPCIONES/LLAVE.WAD",
    "DATOS/RECURSOS/BMPS/SYSTEM/OPCIONES/MANO.WAD",
    "DATOS/RECURSOS/BMPS/SYSTEM/OPCIONES/METRALLE.WAD",
    "DATOS/RECURSOS/BMPS/SYSTEM/OPCIONES/MIRILLA.WAD",
    "DATOS/RECURSOS/BMPS/SYSTEM/OPCIONES/PIOLET.WAD",
    "DATOS/RECURSOS/BMPS/SYSTEM/OPCIONES/PISTOLA.WAD",
    "DATOS/RECURSOS/BMPS/SYSTEM/OPCIONES/SENUELO.WAD",
    "DATOS/RECURSOS/BMPS/SYSTEM/OPCIONES/TRAJEBU.WAD",
    "DATOS/RECURSOS/BMPS/SYSTEM/OPCIONES/UNIFORME.WAD",
    "DATOS/RECURSOS/ELEM/ADOBCLAR.WAD",
    "DATOS/RECURSOS/ELEM/ADOBOSCU.WAD",
    "DATOS/RECURSOS/ELEM/ALAMBRE.WAD",
    "DATOS/RECURSOS/ELEM/ALEGABAR.WAD",
    "DATOS/RECURSOS/ELEM/ALEMAN2.WAD",
    "DATOS/RECURSOS/ELEM/ALEMDES.WAD",
    "DATOS/RECURSOS/ELEM/ALGADES.WAD",
    "DATOS/RECURSOS/ELEM/ANTENA.WAD",
    "DATOS/RECURSOS/ELEM/ARRASTRA.WAD",
    "DATOS/RECURSOS/ELEM/ARTEFACT.WAD",
    "DATOS/RECURSOS/ELEM/ARTIDES.WAD",
    "DATOS/RECURSOS/ELEM/ARTIFIC.WAD",
    "DATOS/RECURSOS/ELEM/AUTOGIRO.WAD",
    "DATOS/RECURSOS/ELEM/BANDERA.WAD",
    "DATOS/RECURSOS/ELEM/BANQUETA.WAD",
    "DATOS/RECURSOS/ELEM/BARCA.WAD",
    "DATOS/RECURSOS/ELEM/BARMAD.WAD",
    "DATOS/RECURSOS/ELEM/BARRACON.WAD",
    "DATOS/RECURSOS/ELEM/BARRE02.WAD",
    "DATOS/RECURSOS/ELEM/BARRERA.WAD",
    "DATOS/RECURSOS/ELEM/BARRIL.WAD",
    "DATOS/RECURSOS/ELEM/BIGDOOR.WAD",
    "DATOS/RECURSOS/ELEM/BISMROT1.WAD",
    "DATOS/RECURSOS/ELEM/BISMROT2.WAD",
    "DATOS/RECURSOS/ELEM/BISMROT3.WAD",
    "DATOS/RECURSOS/ELEM/BISMROT4.WAD",
    "DATOS/RECURSOS/ELEM/BISMROT5.WAD",
    "DATOS/RECURSOS/ELEM/BISMROT6.WAD",
    "DATOS/RECURSOS/ELEM/BOQUETE.WAD",
    "DATOS/RECURSOS/ELEM/BOQUETET.WAD",
    "DATOS/RECURSOS/ELEM/BOYA.WAD",
    "DATOS/RECURSOS/ELEM/CABLE.WAD",
    "DATOS/RECURSOS/ELEM/CABO.WAD",
    "DATOS/RECURSOS/ELEM/CABODES.WAD",
    "DATOS/RECURSOS/ELEM/CABTEL.WAD",
    "DATOS/RECURSOS/ELEM/CAJ1MUN.WAD",
    "DATOS/RECURSOS/ELEM/CAJ2MUN.WAD",
    "DATOS/RECURSOS/ELEM/CAJA.WAD",
    "DATOS/RECURSOS/ELEM/CAJASOM.WAD",
    "DATOS/RECURSOS/ELEM/CAMIALIA.WAD",
    "DATOS/RECURSOS/ELEM/CAMION.WAD",
    "DATOS/RECURSOS/ELEM/CAMIONDES.WAD",
    "DATOS/RECURSOS/ELEM/CANON05.WAD",
    "DATOS/RECURSOS/ELEM/CANON12.WAD",
    "DATOS/RECURSOS/ELEM/CARTUCHO.WAD",
    "DATOS/RECURSOS/ELEM/CEMENTO.WAD",
    "DATOS/RECURSOS/ELEM/CEMTOSCU.WAD",
    "DATOS/RECURSOS/ELEM/CEPO.WAD",
    "DATOS/RECURSOS/ELEM/CHAPA.WAD",
    "DATOS/RECURSOS/ELEM/CHAPAMAR.WAD",
    "DATOS/RECURSOS/ELEM/CHAPBLAN.WAD",
    "DATOS/RECURSOS/ELEM/CHAPGRIS.WAD",
    "DATOS/RECURSOS/ELEM/CHAPMARR.WAD",
    "DATOS/RECURSOS/ELEM/CHAPOTEO.WAD",
    "DATOS/RECURSOS/ELEM/CHAPOXID.WAD",
    "DATOS/RECURSOS/ELEM/CHAPROJA.WAD",
    "DATOS/RECURSOS/ELEM/CHAPVERD.WAD",
    "DATOS/RECURSOS/ELEM/CHARCO.WAD",
    "DATOS/RECURSOS/ELEM/CISTERNA.WAD",
    "DATOS/RECURSOS/ELEM/COCHE.WAD",
    "DATOS/RECURSOS/ELEM/COMADES.WAD",
    "DATOS/RECURSOS/ELEM/COMANDO.WAD",
    "DATOS/RECURSOS/ELEM/CONGLOME.WAD",
    "DATOS/RECURSOS/ELEM/DETONADO.WAD",
    "DATOS/RECURSOS/ELEM/DISPARO.WAD",
    "DATOS/RECURSOS/ELEM/DISPFALL.WAD",
    "DATOS/RECURSOS/ELEM/EMBALAJE.WAD",
    "DATOS/RECURSOS/ELEM/ESC-01.WAD",
    "DATOS/RECURSOS/ELEM/ESCA.WAD",
    "DATOS/RECURSOS/ELEM/ESCLUSA.WAD",
    "DATOS/RECURSOS/ELEM/ESPIA.WAD",
    "DATOS/RECURSOS/ELEM/ESPIAA.WAD",
    "DATOS/RECURSOS/ELEM/EXPLCASA.WAD",
    "DATOS/RECURSOS/ELEM/EXPLOS1.WAD",
    "DATOS/RECURSOS/ELEM/FOCO.WAD",
    "DATOS/RECURSOS/ELEM/FRANCO.WAD",
    "DATOS/RECURSOS/ELEM/FRANDES.WAD",
    "DATOS/RECURSOS/ELEM/FUEGO.WAD",
    "DATOS/RECURSOS/ELEM/FUERTE.WAD",
    "DATOS/RECURSOS/ELEM/FURGONET.WAD",
    "DATOS/RECURSOS/ELEM/GRANADA.WAD",
    "DATOS/RECURSOS/ELEM/GRNDEXPL.WAD",
    "DATOS/RECURSOS/ELEM/HELIC2.WAD",
    "DATOS/RECURSOS/ELEM/HELIC3.WAD",
    "DATOS/RECURSOS/ELEM/HELICDE.WAD",
    "DATOS/RECURSOS/ELEM/HELICE.WAD",
    "DATOS/RECURSOS/ELEM/HELICIZ.WAD",
    "DATOS/RECURSOS/ELEM/HELIZE.WAD",
    "DATOS/RECURSOS/ELEM/HIERAMAR.WAD",
    "DATOS/RECURSOS/ELEM/HIERAZUL.WAD",
    "DATOS/RECURSOS/ELEM/HIEROXID.WAD",
    "DATOS/RECURSOS/ELEM/HIERRAZU.WAD",
    "DATOS/RECURSOS/ELEM/HORCHER.WAD",
    "DATOS/RECURSOS/ELEM/INGEALEM.WAD",
    "DATOS/RECURSOS/ELEM/INTALAM.WAD",
    "DATOS/RECURSOS/ELEM/JEEP.WAD",
    "DATOS/RECURSOS/ELEM/JUNKER.WAD",
    "DATOS/RECURSOS/ELEM/KUBEDES.WAD",
    "DATOS/RECURSOS/ELEM/LADRAMAR.WAD",
    "DATOS/RECURSOS/ELEM/LADRGRIS.WAD",
    "DATOS/RECURSOS/ELEM/LADRILLO.WAD",
    "DATOS/RECURSOS/ELEM/LANCHIST.WAD",
    "DATOS/RECURSOS/ELEM/LANCHON.WAD",
    "DATOS/RECURSOS/ELEM/LANCHON2.WAD",
    "DATOS/RECURSOS/ELEM/LINTENNA.WAD",
    "DATOS/RECURSOS/ELEM/MADEGRIS.WAD",
    "DATOS/RECURSOS/ELEM/MADEOSCU.WAD",
    "DATOS/RECURSOS/ELEM/MADERA.WAD",
    "DATOS/RECURSOS/ELEM/MANCHA15.WAD",
    "DATOS/RECURSOS/ELEM/MECADES.WAD",
    "DATOS/RECURSOS/ELEM/MECANIC.WAD",
    "DATOS/RECURSOS/ELEM/METRALLA.WAD",
    "DATOS/RECURSOS/ELEM/METRBASE.WAD",
    "DATOS/RECURSOS/ELEM/MOLINO.WAD",
    "DATOS/RECURSOS/ELEM/MOTO.WAD",
    "DATOS/RECURSOS/ELEM/MOTODES.WAD",
    "DATOS/RECURSOS/ELEM/MUERT-CD.WAD",
    "DATOS/RECURSOS/ELEM/MUERT-ED.WAD",
    "DATOS/RECURSOS/ELEM/MUERTO.WAD",
    "DATOS/RECURSOS/ELEM/MUERTO-C.WAD",
    "DATOS/RECURSOS/ELEM/NOTOY.WAD",
    "DATOS/RECURSOS/ELEM/NOTOYM.WAD",
    "DATOS/RECURSOS/ELEM/OFICDES.WAD",
    "DATOS/RECURSOS/ELEM/OFICIAL.WAD",
    "DATOS/RECURSOS/ELEM/PBUNK01.WAD",
    "DATOS/RECURSOS/ELEM/PCARC01.WAD",
    "DATOS/RECURSOS/ELEM/PERRO.WAD",
    "DATOS/RECURSOS/ELEM/PESQUERO.WAD",
    "DATOS/RECURSOS/ELEM/PILOTO.WAD",
    "DATOS/RECURSOS/ELEM/PNZ2.WAD",
    "DATOS/RECURSOS/ELEM/PNZ2DIS.WAD",
    "DATOS/RECURSOS/ELEM/PNZ3.WAD",
    "DATOS/RECURSOS/ELEM/PRISION.WAD",
    "DATOS/RECURSOS/ELEM/PUENTE.WAD",
    "DATOS/RECURSOS/ELEM/PUERALAM.WAD",
    "DATOS/RECURSOS/ELEM/PUREJA.WAD",
    "DATOS/RECURSOS/ELEM/RADAR.WAD",
    "DATOS/RECURSOS/ELEM/REJILLA.WAD",
    "DATOS/RECURSOS/ELEM/ROCAS.WAD",
    "DATOS/RECURSOS/ELEM/SANGRE.WAD",
    "DATOS/RECURSOS/ELEM/SDK.WAD",
    "DATOS/RECURSOS/ELEM/SDKDIS.WAD",
    "DATOS/RECURSOS/ELEM/SEGNUELO.WAD",
    "DATOS/RECURSOS/ELEM/SOLDADO.WAD",
    "DATOS/RECURSOS/ELEM/STEY.WAD",
    "DATOS/RECURSOS/ELEM/STUKA.WAD",
    "DATOS/RECURSOS/ELEM/SUBMA.WAD",
    "DATOS/RECURSOS/ELEM/TAN2DES.WAD",
    "DATOS/RECURSOS/ELEM/TANQUETA.WAD",
    "DATOS/RECURSOS/ELEM/TEJAGRIS.WAD",
    "DATOS/RECURSOS/ELEM/TEJAROJA.WAD",
    "DATOS/RECURSOS/ELEM/TELEFONO.WAD",
    "DATOS/RECURSOS/ELEM/TESTIGO.WAD",
    "DATOS/RECURSOS/ELEM/TLANC.WAD",
    "DATOS/RECURSOS/ELEM/TLANCDIS.WAD",
    "DATOS/RECURSOS/ELEM/TORPEDO.WAD",
    "DATOS/RECURSOS/ELEM/TPNZ3.WAD",
    "DATOS/RECURSOS/ELEM/TRANVIA16.WAD",
    "DATOS/RECURSOS/ELEM/TREN.WAD",
    "DATOS/RECURSOS/ELEM/TREN2.WAD",
    "DATOS/RECURSOS/ELEM/TT2DES.WAD",
    "DATOS/RECURSOS/ELEM/T-TANQTA.WAD",
    "DATOS/RECURSOS/ELEM/UNIFORME.WAD",
    "DATOS/RECURSOS/ELEM/VAGON.WAD",
    "DATOS/RECURSOS/ELEM/VAGON1.WAD",
    "DATOS/RECURSOS/ELEM/VAGON2.WAD",
    "DATOS/RECURSOS/ELEM/VAGON3.WAD",
    "DATOS/RECURSOS/ELEM/VAGONETA.WAD",
    "DATOS/RECURSOS/ELEM/VOLQUETE.WAD",
    "DATOS/RECURSOS/ELEM/ZODIAC2.WAD",
};

std::vector<std::string> misFilePaths = {
    "DATOS/MISIONES/MAPA0000.MIS",
    "DATOS/MISIONES/MAPA0001.MIS",
    "DATOS/MISIONES/MAPA0002.MIS",
    "DATOS/MISIONES/MAPA0003.MIS",
    "DATOS/MISIONES/MAPA0004.MIS",
    "DATOS/MISIONES/MAPA0005.MIS",
    "DATOS/MISIONES/MAPA0006.MIS",
    "DATOS/MISIONES/MAPA0007.MIS",
    "DATOS/MISIONES/MAPA0008.MIS",
    "DATOS/MISIONES/MAPA0009.MIS",
    "DATOS/MISIONES/MAPA0010.MIS",
    "DATOS/MISIONES/MAPA0011.MIS",
    "DATOS/MISIONES/MAPA0012.MIS",
    "DATOS/MISIONES/MAPA0013.MIS",
    "DATOS/MISIONES/MAPA0014.MIS",
    "DATOS/MISIONES/MAPA0015.MIS",
    "DATOS/MISIONES/MAPA0016.MIS",
    "DATOS/MISIONES/MAPA0017.MIS",
    "DATOS/MISIONES/MAPA0018.MIS",
    "DATOS/MISIONES/MAPA0019.MIS",
    "DATOS/MISIONES/MAPA0020.MIS",
    "DATOS/MISIONES/MAPA0021.MIS",
    "DATOS/MISIONES/MAPA0022.MIS",
    "DATOS/MISIONES/MAPA0023.MIS",
    "DATOS/MISIONES/MAPA0024.MIS",
    "DATOS/MISIONES/MAPA0025.MIS",
    "DATOS/MISIONES/MAPA0026.MIS",
};

int main()
{
  const int windowWidth = 800;
  const int windowHeight = 600;
  const int buttonWidth = 200;
  const int buttonHeight = 32;
  const int buttonOffset = 6;

  int misFileIndex = -1;
  bool misFileDropdownEditMode = false;

  InitWindow(windowWidth, windowHeight, "openCommandos");
  SetTargetFPS(60);

  while (!WindowShouldClose())
  {
    BeginDrawing();
    ClearBackground(RAYWHITE);

    DrawText("Hello openCommandos!", 20, 20, 20, BLACK);

    if (GuiButton(
            (Rectangle){
                20,
                20 + (buttonHeight + buttonOffset) * 1,
                buttonWidth,
                buttonHeight},
            "#7#Extract .DIR file"))
    {
      for (int i = 0; i < dirFilePaths.size(); i++)
      {
        DirFile dirFile = DirFile(dirFilePaths.at(i));
        dirFile.Extract();
      }
    }

    if (GuiButton(
            (Rectangle){
                20,
                20 + (buttonHeight + buttonOffset) * 2,
                buttonWidth,
                buttonHeight},
            "#7#Extract .WAD files"))
    {
      for (int i = 0; i < wadFilePaths.size(); i++)
      {
        WadFile wadFile = WadFile(wadFilePaths.at(i));
        wadFile.Extract();
      }
    }

    if (GuiButton(
            (Rectangle){
                20,
                20 + (buttonHeight + buttonOffset) * 3,
                buttonWidth,
                buttonHeight},
            "#7#Extract .MIS file"))
    {
      MisFile misFile = MisFile(misFilePaths.at(misFileIndex));
      misFile.Parse();
      std::string volFileName = misFile.GetRoot()
                                    ->GetNode(".FASE0000")
                                    ->GetNode(".DATOSFICHEROSMISION")
                                    ->GetNode(".VOLUMENES")
                                    ->GetString();
      TraceLog(LOG_INFO, volFileName.c_str());
    }

    if (GuiValueBox(
            (Rectangle){
                20 + buttonWidth,
                20 + (buttonHeight + buttonOffset) * 3,
                40,
                buttonHeight},
            "",
            &misFileIndex,
            0,
            misFilePaths.size(),
            misFileDropdownEditMode))
    {
      misFileDropdownEditMode = !misFileDropdownEditMode;
    }

    EndDrawing();
  }

  CloseWindow();
  return 0;
}
